app:
  cors:
    allowedOrigins: http://localhost:3000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhteo2903@gmail.com
    password: fshgdyykathxyjfr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://localhost:3306/jobsgo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # 1 day
        refresh-token:
          expiration: 604800000 # 7 day
